#!/usr/bin/env bash
# ensembleworks-cli devcontainer feature installer. Runs at image build as root,
# feature dir as cwd. Option values arrive as uppercased env vars
# (url->URL, gatewayLabel->GATEWAYLABEL, gatewayId->GATEWAYID,
#  tokenId->TOKENID, tokenSecret->TOKENSECRET, version->VERSION).
set -euo pipefail

REPO="lean-software-production/ensembleworks"
VER="${VERSION:-latest}"
SHARE="/usr/local/share/ensembleworks-connect"

# 1. tmux (the connector spawns tmux sessions; same as the old feature).
if ! command -v tmux >/dev/null; then
	apt-get update && apt-get install -y --no-install-recommends tmux ca-certificates curl
	rm -rf /var/lib/apt/lists/*
fi

# 2. Fetch + checksum-verify the ensembleworks binary for THIS container's arch
#    (Linux only inside a container). Adapted from deploy/install.sh; installs
#    system-wide as root instead of ~/.local/bin as the user.
case "$(uname -s)-$(uname -m)" in
Linux-x86_64) A=linux-x64 ;;
Linux-aarch64) A=linux-arm64 ;;
*) echo "ensembleworks-cli: unsupported container platform $(uname -sm)" >&2; exit 1 ;;
esac
base="https://github.com/$REPO/releases/latest/download"
[ "$VER" = latest ] || base="https://github.com/$REPO/releases/download/v$VER"
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
curl -fsSL "$base/ensembleworks-$A" -o "$tmp/ew"
curl -fsSL "$base/ensembleworks-checksums.txt" -o "$tmp/sums"
(cd "$tmp" && grep " ensembleworks-$A\$" sums | sed "s/ensembleworks-$A/ew/" | sha256sum -c -)
install -D -m 0755 "$tmp/ew" /usr/local/bin/ensembleworks
ln -f /usr/local/bin/ensembleworks /usr/local/bin/ew

# 3. Ship the supervisor, entrypoint, and tmux conf (self-contained: the conf is
#    a committed copy of deploy/tmux-ensembleworks.conf — spec §5.1).
install -D -m 0755 ./supervisor.sh "$SHARE/supervisor.sh"
install -D -m 0755 ./entrypoint.sh "$SHARE/entrypoint.sh"
install -D -m 0644 ./tmux-ensembleworks.conf "$SHARE/tmux-ensembleworks.conf"

# 4. Bake the NON-SECRET connector config into an env file the supervisor
#    sources at runtime. Options are baked at BUILD time (no reliance on
#    remoteEnv reaching a backgrounded daemon — spec §4).
#    emit KEY='value', single-quoting so labels with spaces survive `.` sourcing
#    (the old feature's lesson: an unquoted space ran the tail as a command).
emit() {
	[ -n "$2" ] || return 0
	printf "%s='%s'\n" "$1" "$(printf '%s' "$2" | sed "s/'/'\\\\''/g")"
}
{
	echo "# generated by ensembleworks-cli feature install.sh"
	emit ENSEMBLEWORKS_URL "${URL:-}"
	emit EW_LABEL "${GATEWAYLABEL:-}"
	emit EW_GATEWAY_ID "${GATEWAYID:-}"
	# SECURITY (spec §4): only baked when the operator set the option. Prefer
	# runtime env injection — a baked secret is readable in the image layer.
	emit ENSEMBLEWORKS_TOKEN_ID "${TOKENID:-}"
	emit ENSEMBLEWORKS_TOKEN_SECRET "${TOKENSECRET:-}"
	emit TMUX_CONF "$SHARE/tmux-ensembleworks.conf"
} >/etc/ensembleworks-connect.env
# 0600, root-owned: this file CAN carry a baked token (spec §4 escape hatch) on
# a box that hosts arbitrary canvas terminals. 0600 keeps a terminal user from
# reading it. The URL isn't sensitive, but always-0600 is harmless and removes a
# mode-branch. The supervisor runs as root (entrypoint is root at container
# init), so root ownership is the correct run-as owner.
chmod 0600 /etc/ensembleworks-connect.env

echo "ensembleworks-cli feature installed (version=${VER}, arch=${A}, url=${URL:-<runtime>})"
