#!/usr/bin/env bash
# Devcontainer feature installer: runs at image build as root, with this
# feature's files as the working directory. Feature option values arrive as
# uppercased env vars (canvasUrl -> CANVASURL, ...).
set -euo pipefail

if ! command -v tmux >/dev/null; then
	apt-get update && apt-get install -y --no-install-recommends tmux && rm -rf /var/lib/apt/lists/*
fi

install -D -m 0755 ./dist/termgw /usr/local/bin/termgw
install -D -m 0755 ./termgw-supervisor.sh /usr/local/share/termgw/termgw-supervisor.sh
install -D -m 0755 ./termgw-entrypoint.sh /usr/local/share/termgw/termgw-entrypoint.sh
# Optional tmux conf: ship the repo conf when present beside the feature.
if [ -f ./tmux.conf ]; then
	install -D -m 0644 ./tmux.conf /usr/local/share/termgw/tmux.conf
fi

# Bake the connector config into an env file the supervisor sources at runtime.
# Options are baked at BUILD time, so the connector needs no remoteEnv /
# lifecycle-hook env propagation (which does not reliably reach a backgrounded
# daemon). CANVASURL/GATEWAYLABEL/GATEWAYID come from the feature options.
#
# emit a shell-sourceable KEY='value' line, single-quoting the value so labels
# with spaces (e.g. "workshops box") survive `. /etc/termgw.env` — an unquoted
# space made the value's tail run as a command and left the var unset.
emit() {
	[ -n "$2" ] || return 0
	printf "%s='%s'\n" "$1" "$(printf '%s' "$2" | sed "s/'/'\\\\''/g")"
}
{
	echo "# generated by termgw feature install.sh"
	emit CANVAS_URL "${CANVASURL:-}"
	emit GATEWAY_LABEL "${GATEWAYLABEL:-}"
	emit GATEWAY_ID "${GATEWAYID:-}"
	emit TMUX_CONF "/usr/local/share/termgw/tmux.conf"
} >/etc/termgw.env
chmod 0644 /etc/termgw.env

echo "termgw feature installed (canvasUrl=${CANVASURL:-<unset>})"
